const STORE = [{
    image: ["hero_image", "assets/notes_wall.png", "image showing a wall of post-it notes"],
    date_created: 'formed on the twenty-second of april in the year of our Lord twenty-twenty',
    title: "the cost of of authenticity",
    content:    `i recently put up sticky notes on my wall next to my bed. the purpose was to see which people that stopped talknig to me for various reasons. all were people i did not prefer to cease communication wiht. i miss each of them. i like to see the good in everyone because i think everyone is good. it's only when we think we're not that there are problems. that's what i've come to believe in the past year. it's how i've been able to practice compassion towards myself.
                a name is written on each note. the names are if the people i showed up to. not the version i wanted them to see. not the projection i wanted to craft. i showed as i was. as i am. my intention was to be as authentic as possible. to be as 'me' as possible. and it does not seem to be the magic key to gain access to anyone. it has actually been totally polarizing. i seem to be either accepted or outright rejected. no chat here and there. no message once in a while. no contanct.
                while it hurts. these notes, small and yellow, show i am trying. i am putting myself out there. to be seen. i show up. and i'm messing and incomplete and totally behind. but i respect everyone enough to show them who i am. not who i want them to see. no picking choice words or perfectly timed photos. no agenda. no wants. and it seems that some are saying 'no thanks'. and the hurt i feel shows me what it is i was actually postering for... me. i was using people to determine my
                worth that moment. i counted bodies as how well i was progressing socially. i never considered what it is they want. who they want in their lives for whatever reason. i thought there shouldn't be any reason why someone would not want to be my friend. because i wanted to be a guy that everyone liked. because then i would know i was right where i was supposed to be. i never thought that rejection was the way to becoming a better person. i kept myself from being rejected to stay safe.
                and since i've emerged from the shadows, shown a light on myself, i have exposed myself to rejection. i gave someone the choice to say 'no'. i see how obsessed with control i am. i always felt different from others. like i did not belong. and i made it come true. i proved it in a way. not that i am a 'bad' person but that i destroyed myself by myself. by my own hand. <span class="highlight">in trying to get everyone to like me i've gotten everyone to hate me</span>.  i just wanted
                to be loved and accepted. to be sought after. to be admired. i've gotten so far off course that i don't even know what it feels like to be going in the right direction. i do thank God for the mercy He has shown me. letting go has been the most difficult thing i've ever had to do. to let go of all outcomes. to be subject to the universe...<span class="insight">life is 10% what happens and 90% how you react</span>. i've seen just as many people accept me as i actually am — past and all.
                So i cannot say i'm worthless. i also can't say i'm a loser. Jesus had many enemies. and i am in no way comparing myself to Him. i see that it is impossible for anyone, even God Himself, to be liked and loved. i destroyed my life trying to do it. my whole life has been built around this mission. and i know there are countless people out there that will reject me in the future. but there are also just as many people that will be grateful to have me in their life. just as i will appreciate
                their presence in mine. i love all the people who do not talk to me anymore. i've decided instead to remember them by the positive contribution they made to my life. whether they were 'daring' or 'thoughtful' or 'fearless'. they all taught me to love myself. they all were loveable. i am so grateful i had space in their lives. because they are all so brilliant in their own way. i want to be a better person for them. i want to be the thing that maybe they thought i wasn't. i am trying today.
                and i see how difficult it is to do so. but it's what i've always wanted to do. and it's what's most respectful of other people. my mission today is to love myself. because i cannot mine pleasure and acceptance from others. it's not fair for either for anyone.`
}]